class ExpenseConstants:
  # Commands constants.
  MOVE_IN = "MOVE_IN"
  MOVE_OUT = "MOVE_OUT"
  SPEND = "SPEND"
  DUES = "DUES"
  CLEAR_DUE = "CLEAR_DUE"

  # OUTPUT CONSTANTS
  SUCCESS = "SUCCESS"
  HOUSEFUL = "HOUSEFUL"
  MEMBER_NOT_FOUND = "MEMBER_NOT_FOUND"
  INCORRECT_PAYMENT = "INCORRECT_PAYMENT"
  FAILURE = "FAILURE"
  
